import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';
import 'package:yaml/yaml.dart';

import 'localization_manifest.dart';

void main() {
  final root = projectRoot();
  final manifest = loadLocalizationManifest(root);
  final enabled = manifest.enabledLanguages;

  for (final language in enabled) {
    final source = File(
      '${root.path}/localization/${language.directoryName}/strings.arb',
    );
    if (!source.existsSync()) {
      throw StateError('Missing language pack: ${source.path}');
    }
    source.copySync('${root.path}/lib/l10n/${language.arbFileName}');
    _writeNativeResources(root, language);
  }

  _writeRegistry(root, enabled);
  _writeBuiltInExercises(root, enabled);
  _writeAndroidLocaleConfig(root, enabled);
  _updateXcodeProject(root, enabled);
  stdout.writeln('Generated ${enabled.length} enabled language packs.');
}

void _writeBuiltInExercises(
  Directory root,
  List<LanguageDefinition> languages,
) {
  final catalogFile = File('${root.path}/localization/exercises.yaml');
  final catalog = loadYaml(catalogFile.readAsStringSync()) as YamlMap;
  final exercises = catalog['exercises'] as YamlMap;
  final translations = <String, YamlMap>{};
  for (final language in languages) {
    final file = File(
      '${root.path}/localization/${language.directoryName}/exercises.yaml',
    );
    translations[language.flutterLocale] = loadYaml(file.readAsStringSync()) as YamlMap;
  }

  final buffer = StringBuffer()
    ..writeln('// Generated by localization/tools/generate.dart. Do not edit.')
    ..writeln()
    ..writeln('final class BuiltInExerciseText {')
    ..writeln('  const BuiltInExerciseText({')
    ..writeln('    required this.name,')
    ..writeln('    required this.bodyPart,')
    ..writeln('    required this.equipment,')
    ..writeln('    required this.primaryMuscles,')
    ..writeln('    required this.description,')
    ..writeln('  });')
    ..writeln()
    ..writeln('  final String name;')
    ..writeln('  final String bodyPart;')
    ..writeln('  final String equipment;')
    ..writeln('  final String primaryMuscles;')
    ..writeln('  final String description;')
    ..writeln('}')
    ..writeln()
    ..writeln("const builtInExercisePrefix = 'built_in:';")
    ..writeln()
    ..writeln('const builtInExerciseKeyByRemoteId = <int, String>{');
  for (final entry in exercises.entries) {
    final metadata = entry.value as YamlMap;
    buffer.writeln(
      '  ${metadata['remote_id']}: ${_dartString(entry.key as String)},',
    );
  }
  buffer
    ..writeln('};')
    ..writeln()
    ..writeln('const builtInExerciseLegacyKeyByName = <String, String>{');
  final writtenAliases = <String>{};
  for (final entry in exercises.entries) {
    final key = entry.key as String;
    final metadata = entry.value as YamlMap;
    for (final name in (metadata['legacy_names'] as YamlList).cast<String>()) {
      final normalized = _normalizeExerciseName(name);
      if (!writtenAliases.add(normalized)) {
        continue;
      }
      buffer.writeln(
        '  ${_dartString(normalized)}: ${_dartString(key)},',
      );
    }
    for (final pack in translations.values) {
      final text = pack[key] as YamlMap;
      final normalized = _normalizeExerciseName(text['name'] as String);
      if (!writtenAliases.add(normalized)) {
        continue;
      }
      buffer.writeln(
        '  ${_dartString(normalized)}: ${_dartString(key)},',
      );
    }
  }
  buffer
    ..writeln('};')
    ..writeln()
    ..writeln(
      'const builtInExerciseTexts = <String, Map<String, BuiltInExerciseText>>{',
    );
  for (final language in languages) {
    final pack = translations[language.flutterLocale]!;
    buffer.writeln('  ${_dartString(language.flutterLocale)}: {');
    for (final key in exercises.keys.cast<String>()) {
      final text = pack[key] as YamlMap;
      buffer
        ..writeln('    ${_dartString(key)}: BuiltInExerciseText(')
        ..writeln('      name: ${_dartString(text['name'] as String)},')
        ..writeln(
          '      bodyPart: ${_dartString(text['body_part'] as String)},',
        )
        ..writeln(
          '      equipment: ${_dartString(text['equipment'] as String)},',
        )
        ..writeln(
          '      primaryMuscles: ${_dartString(text['primary_muscles'] as String)},',
        )
        ..writeln(
          '      description: ${_dartString(text['description'] as String)},',
        )
        ..writeln('    ),');
    }
    buffer.writeln('  },');
  }
  buffer.writeln('};');

  final output = File(
    '${root.path}/lib/redesign/localization/generated_built_in_exercises.dart',
  )..writeAsStringSync(buffer.toString());
  final formatResult = Process.runSync('dart', ['format', output.path]);
  if (formatResult.exitCode != 0) {
    throw StateError('Failed to format ${output.path}: ${formatResult.stderr}');
  }
}

String _normalizeExerciseName(String value) => value
    .trim()
    .toLowerCase()
    .replaceAll(RegExp(r'[\u2010-\u2015]'), '-')
    .replaceAll(RegExp(r'[^a-z0-9\u3040-\u30ff\u3400-\u9fff]+'), ' ')
    .replaceAll(RegExp(r'\s+'), ' ')
    .trim();

void _writeRegistry(Directory root, List<LanguageDefinition> languages) {
  final buffer = StringBuffer()
    ..writeln('// Generated by localization/tools/generate.dart. Do not edit.')
    ..writeln("import 'package:flutter/widgets.dart';")
    ..writeln()
    ..writeln('final class YoursLanguage {')
    ..writeln('  const YoursLanguage({')
    ..writeln('    required this.locale,')
    ..writeln('    required this.nativeName,')
    ..writeln('  });')
    ..writeln()
    ..writeln('  final Locale locale;')
    ..writeln('  final String nativeName;')
    ..writeln('}')
    ..writeln()
    ..writeln('const yoursSupportedLanguages = <YoursLanguage>[');
  for (final language in languages) {
    final parts = language.flutterLocale.split(RegExp('[-_]'));
    final locale = parts.length == 1
        ? "Locale('${parts.first}')"
        : "Locale('${parts.first}', '${parts[1]}')";
    buffer.writeln(
      '  YoursLanguage(locale: $locale, nativeName: ${_dartString(language.nativeName)}),',
    );
  }
  buffer
    ..writeln('];')
    ..writeln()
    ..writeln(
      'const yoursSupportedLocales = <Locale>[',
    );
  for (final language in languages) {
    final parts = language.flutterLocale.split(RegExp('[-_]'));
    final locale = parts.length == 1
        ? "Locale('${parts.first}')"
        : "Locale('${parts.first}', '${parts[1]}')";
    buffer.writeln('  $locale,');
  }
  buffer.writeln('];');

  File(
    '${root.path}/lib/redesign/localization/generated_language_registry.dart',
  ).writeAsStringSync(buffer.toString());
}

void _writeNativeResources(Directory root, LanguageDefinition language) {
  final platformFile = File(
    '${root.path}/localization/${language.directoryName}/platform.yaml',
  );
  final platform = loadYaml(platformFile.readAsStringSync()) as YamlMap;
  final iosDirectory = Directory(
    '${root.path}/ios/Runner/${language.locale}.lproj',
  )..createSync(recursive: true);
  File('${iosDirectory.path}/InfoPlist.strings').writeAsStringSync(
    [
      _appleString('CFBundleDisplayName', platform['app_name'] as String),
      _appleString('CFBundleName', platform['app_name'] as String),
      _appleString(
        'NSUbiquitousContainerName',
        platform['icloud_container_name'] as String,
      ),
      _appleString(
        'NSCameraUsageDescription',
        platform['camera_usage'] as String,
      ),
      _appleString(
        'NSPhotoLibraryUsageDescription',
        platform['photo_library_usage'] as String,
      ),
      '',
    ].join('\n'),
  );
  final messages = platform['native_messages'] as YamlMap;
  File('${iosDirectory.path}/Localizable.strings').writeAsStringSync(
    [
      for (final entry in messages.entries)
        _appleString(entry.key as String, entry.value as String),
      '',
    ].join('\n'),
  );

  final androidQualifier = language.flutterLocale == 'en'
      ? 'values'
      : 'values-${language.flutterLocale}';
  final androidDirectory = Directory(
    '${root.path}/android/app/src/main/res/$androidQualifier',
  )..createSync(recursive: true);
  File('${androidDirectory.path}/strings.xml').writeAsStringSync(
    '<resources>\n'
    '    <string name="app_name">${_xmlEscape(platform['app_name'] as String)}</string>\n'
    '</resources>\n',
  );
}

void _writeAndroidLocaleConfig(
  Directory root,
  List<LanguageDefinition> languages,
) {
  final buffer = StringBuffer()
    ..writeln('<?xml version="1.0" encoding="utf-8"?>')
    ..writeln('<locale-config xmlns:android="http://schemas.android.com/apk/res/android">');
  for (final language in languages) {
    buffer.writeln('    <locale android:name="${language.flutterLocale}"/>');
  }
  buffer.writeln('</locale-config>');
  File(
    '${root.path}/android/app/src/main/res/xml/locales_config.xml',
  ).writeAsStringSync(buffer.toString());
}

void _updateXcodeProject(
  Directory root,
  List<LanguageDefinition> languages,
) {
  final projectFile = File('${root.path}/ios/Runner.xcodeproj/project.pbxproj');
  var project = projectFile.readAsStringSync();
  for (final language in languages) {
    final locale = language.locale;
    final quotedLocale = locale.contains('-') ? '"$locale"' : locale;
    if (!RegExp(
      r'^\s*' + RegExp.escape(quotedLocale) + r',\s*$',
      multiLine: true,
    ).hasMatch(project)) {
      project = project.replaceFirst(
        '\t\t\t\tBase,\n',
        '\t\t\t\t$quotedLocale,\n\t\t\t\tBase,\n',
      );
    }

    final infoPath = '$locale.lproj/InfoPlist.strings';
    final localizablePath = '$locale.lproj/Localizable.strings';
    final infoId = _xcodeId('InfoPlist:$locale');
    final localizableId = _xcodeId('Localizable:$locale');
    if (!project.contains('path = ${_xcodeValue(infoPath)};')) {
      final references = StringBuffer()
        ..writeln(
          '\t\t$infoId /* $locale */ = {isa = PBXFileReference; '
          'lastKnownFileType = text.plist.strings; name = $quotedLocale; '
          'path = ${_xcodeValue(infoPath)}; sourceTree = "<group>"; };',
        )
        ..writeln(
          '\t\t$localizableId /* $locale */ = {isa = PBXFileReference; '
          'lastKnownFileType = text.plist.strings; name = $quotedLocale; '
          'path = ${_xcodeValue(localizablePath)}; sourceTree = "<group>"; };',
        );
      project = project.replaceFirst(
        '/* End PBXFileReference section */',
        '$references/* End PBXFileReference section */',
      );
      project = _addVariantChild(
        project,
        groupName: 'InfoPlist.strings',
        child: '\t\t\t\t$infoId /* $locale */,\n',
      );
      project = _addVariantChild(
        project,
        groupName: 'Localizable.strings',
        child: '\t\t\t\t$localizableId /* $locale */,\n',
      );
    }
  }
  projectFile.writeAsStringSync(project);
}

String _addVariantChild(
  String project, {
  required String groupName,
  required String child,
}) {
  final groupPattern = RegExp(
    r'(\/\* ' +
        RegExp.escape(groupName) +
        r' \*\/ = \{\s+isa = PBXVariantGroup;\s+children = \(\s*)(.*?)(\s+\);)',
    dotAll: true,
  );
  return project.replaceFirstMapped(groupPattern, (match) {
    final existing = match.group(2)!;
    if (existing.contains(child.trim())) {
      return match.group(0)!;
    }
    return '${match.group(1)}$existing\n$child${match.group(3)}';
  });
}

String _xcodeId(String seed) =>
    sha1.convert(utf8.encode('yours-localization:$seed')).toString().substring(0, 24).toUpperCase();

String _xcodeValue(String value) => value.contains('-') ? '"$value"' : value;

String _appleString(String key, String value) {
  final escaped = value.replaceAll(r'\', r'\\').replaceAll('"', r'\"');
  return '"$key" = "$escaped";';
}

String _xmlEscape(String value) => const HtmlEscape(HtmlEscapeMode.element).convert(value);

String _dartString(String value) => "'${value.replaceAll(r'\', r'\\').replaceAll("'", r"\'")}'";
