// Generated by localization/tools/generate.dart. Do not edit.
import 'package:flutter/widgets.dart';

final class YoursLanguage {
  const YoursLanguage({
    required this.locale,
    required this.nativeName,
  });

  final Locale locale;
  final String nativeName;
}

const yoursSupportedLanguages = <YoursLanguage>[
  YoursLanguage(locale: Locale('zh'), nativeName: '简体中文'),
  YoursLanguage(locale: Locale('en'), nativeName: 'English'),
  YoursLanguage(locale: Locale('ja'), nativeName: '日本語'),
];

const yoursSupportedLocales = <Locale>[
  Locale('zh'),
  Locale('en'),
  Locale('ja'),
];
