// Generated by localization/tools/generate.dart. Do not edit.

final class BuiltInExerciseText {
  const BuiltInExerciseText({
    required this.name,
    required this.bodyPart,
    required this.equipment,
    required this.primaryMuscles,
    required this.description,
  });

  final String name;
  final String bodyPart;
  final String equipment;
  final String primaryMuscles;
  final String description;
}

const builtInExercisePrefix = 'built_in:';

const builtInExerciseKeyByRemoteId = <int, String>{
  73: 'bench_press',
  184: 'deadlift',
  348: 'lateral_raise',
  615: 'barbell_squat',
  458: 'plank',
};

const builtInExerciseLegacyKeyByName = <String, String>{
  '杠铃卧推': 'bench_press',
  'bench press': 'bench_press',
  'barbell bench press': 'bench_press',
  'ベンチプレス': 'bench_press',
  '传统硬拉': 'deadlift',
  'deadlift': 'deadlift',
  'deadlifts': 'deadlift',
  'デッドリフト': 'deadlift',
  '哑铃侧平举': 'lateral_raise',
  'lateral raise': 'lateral_raise',
  'lateral raises': 'lateral_raise',
  'ダンベルサイドレイズ': 'lateral_raise',
  '杠铃深蹲': 'barbell_squat',
  '深蹲': 'barbell_squat',
  'barbell squat': 'barbell_squat',
  'squat': 'barbell_squat',
  'squats': 'barbell_squat',
  'バーベルスクワット': 'barbell_squat',
  '平板支撑': 'plank',
  'plank': 'plank',
  'プランク': 'plank',
};

const builtInExerciseTexts = <String, Map<String, BuiltInExerciseText>>{
  'zh': {
    'bench_press': BuiltInExerciseText(
      name: '杠铃卧推',
      bodyPart: '胸',
      equipment: '卧推凳、杠铃',
      primaryMuscles: '胸大肌 · 三头肌 · 三角肌前束',
      description: '仰卧在卧推凳上，稳定肩胛，控制杠铃下降至胸前，再用胸部和三头肌协同推起。',
    ),
    'deadlift': BuiltInExerciseText(
      name: '传统硬拉',
      bodyPart: '背',
      equipment: '杠铃',
      primaryMuscles: '后侧链 · 背部 · 核心',
      description: '靠近杠铃站立，保持背部中立，髋膝协同伸展将杠铃拉起，再有控制地下放。',
    ),
    'lateral_raise': BuiltInExerciseText(
      name: '哑铃侧平举',
      bodyPart: '肩',
      equipment: '哑铃',
      primaryMuscles: '三角肌中束',
      description: '手肘微屈，将哑铃向身体两侧抬起至接近肩高，稍停后有控制地下放。',
    ),
    'barbell_squat': BuiltInExerciseText(
      name: '杠铃深蹲',
      bodyPart: '腿',
      equipment: '杠铃',
      primaryMuscles: '股四头肌 · 臀部 · 核心',
      description: '保持核心收紧，膝盖沿脚尖方向下蹲，再有控制地站起。',
    ),
    'plank': BuiltInExerciseText(
      name: '平板支撑',
      bodyPart: '核心',
      equipment: '自重',
      primaryMuscles: '腹肌 · 腹斜肌 · 核心稳定',
      description: '用前臂支撑，身体保持直线，收紧核心并避免塌腰。',
    ),
  },
  'en': {
    'bench_press': BuiltInExerciseText(
      name: 'Bench Press',
      bodyPart: 'Chest',
      equipment: 'Bench · Barbell',
      primaryMuscles: 'Pectorals · Triceps · Front deltoids',
      description:
          'Lie on the bench with your shoulder blades set. Lower the bar under control, then press it up using your chest and triceps.',
    ),
    'deadlift': BuiltInExerciseText(
      name: 'Deadlift',
      bodyPart: 'Back',
      equipment: 'Barbell',
      primaryMuscles: 'Posterior chain · Back · Core',
      description:
          'Stand close to the bar, keep your back neutral, and extend your hips and knees together before lowering the bar with control.',
    ),
    'lateral_raise': BuiltInExerciseText(
      name: 'Lateral Raise',
      bodyPart: 'Shoulders',
      equipment: 'Dumbbells',
      primaryMuscles: 'Lateral deltoids',
      description:
          'Raise the dumbbells out to the sides with a slight bend in the elbows, pause near shoulder height, then lower with control.',
    ),
    'barbell_squat': BuiltInExerciseText(
      name: 'Barbell Squat',
      bodyPart: 'Legs',
      equipment: 'Barbell',
      primaryMuscles: 'Quadriceps · Glutes · Core',
      description:
          'Keep your core braced as you squat with your knees tracking over your toes, then stand back up under control.',
    ),
    'plank': BuiltInExerciseText(
      name: 'Plank',
      bodyPart: 'Core',
      equipment: 'Bodyweight',
      primaryMuscles: 'Abdominals · Obliques · Core stability',
      description:
          'Support yourself on your forearms, keep your body in a straight line, and brace your core without letting your hips sag.',
    ),
  },
  'ja': {
    'bench_press': BuiltInExerciseText(
      name: 'ベンチプレス',
      bodyPart: '胸',
      equipment: 'ベンチ · バーベル',
      primaryMuscles: '大胸筋 · 上腕三頭筋 · 三角筋前部',
      description: '肩甲骨を安定させてベンチに仰向けになり、バーベルを胸元までコントロールして下ろした後、胸と上腕三頭筋を使って押し上げます。',
    ),
    'deadlift': BuiltInExerciseText(
      name: 'デッドリフト',
      bodyPart: '背中',
      equipment: 'バーベル',
      primaryMuscles: 'ポステリアチェーン · 背中 · 体幹',
      description: 'バーベルの近くに立ち、背中をまっすぐに保ちながら股関節と膝を同時に伸ばし、コントロールして下ろします。',
    ),
    'lateral_raise': BuiltInExerciseText(
      name: 'ダンベルサイドレイズ',
      bodyPart: '肩',
      equipment: 'ダンベル',
      primaryMuscles: '三角筋中部',
      description: '肘を軽く曲げ、ダンベルを肩の高さ付近まで横に上げてから、コントロールして下ろします。',
    ),
    'barbell_squat': BuiltInExerciseText(
      name: 'バーベルスクワット',
      bodyPart: '脚',
      equipment: 'バーベル',
      primaryMuscles: '大腿四頭筋 · 臀筋 · 体幹',
      description: '体幹を安定させ、膝をつま先の方向に合わせてしゃがみ、コントロールして立ち上がります。',
    ),
    'plank': BuiltInExerciseText(
      name: 'プランク',
      bodyPart: '体幹',
      equipment: '自重',
      primaryMuscles: '腹筋 · 腹斜筋 · 体幹安定',
      description: '前腕で体を支えて一直線を保ち、腰が落ちないように体幹を引き締めます。',
    ),
  },
};
